swagger: "2.0"
info:
  title: "Email API"
  version: "1.0.0"
host: "emailapi.endpoints.isentropic-card-423523-k4.cloud.goog"
schemes:
  - http
  - https
paths:
  /:
    get:
      summary: "Root endpoint"
      operationId: "getRoot"
      responses:
        200:
          description: "Success"

x-google-endpoints:
  - name: "emailapi.endpoints.isentropic-card-423523-k4.cloud.goog"
    target: "34.133.202.227"

